"""add edge room id

Revision ID: 538c92eb5351
Revises: f7d07d069526
Create Date: 2025-02-16 20:04:24.207443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '538c92eb5351'
down_revision: Union[str, None] = 'f7d07d069526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edge', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'edge', 'room', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'edge', type_='foreignkey')
    op.drop_column('edge', 'room_id')
    # ### end Alembic commands ###
