"""add node

Revision ID: 5792156ae0c2
Revises: 688bc5b657cd
Create Date: 2025-02-16 19:25:47.238720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5792156ae0c2'
down_revision: Union[str, None] = '688bc5b657cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('floor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.ForeignKeyConstraint(['floor_id'], ['floor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_id'), 'edge', ['id'], unique=False)
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('node_type', sa.Enum('ROOM', 'CONNECTION_POINT', name='nodetypeenum'), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('floor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.ForeignKeyConstraint(['floor_id'], ['floor.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_id'), 'node', ['id'], unique=False)
    op.create_table('adjacency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('edge_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edge_id'], ['edge.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adjacency_id'), 'adjacency', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adjacency_id'), table_name='adjacency')
    op.drop_table('adjacency')
    op.drop_index(op.f('ix_node_id'), table_name='node')
    op.drop_table('node')
    op.drop_index(op.f('ix_edge_id'), table_name='edge')
    op.drop_table('edge')
    # ### end Alembic commands ###
