"""Created Buildings

Revision ID: 688bc5b657cd
Revises: 9c5821c200db
Create Date: 2025-02-03 14:43:36.914835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '688bc5b657cd'
down_revision: Union[str, None] = '9c5821c200db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('rendering_entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rendering_entity_id'], ['renderingentity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_building_id'), 'building', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_building_id'), table_name='building')
    op.drop_table('building')
    # ### end Alembic commands ###
