"""Add roomType to room table

Revision ID: 6b3a55bc2e20
Revises: 46c01e3eb325
Create Date: 2025-03-04 22:43:05.644415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b3a55bc2e20'
down_revision: Union[str, None] = '46c01e3eb325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('room_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'room_type')
    # ### end Alembic commands ###
