"""create rendering_entity parent

Revision ID: 7ee140c8c3ec
Revises: bdd07dc4beb0
Create Date: 2025-01-25 19:04:59.293127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ee140c8c3ec'
down_revision: Union[str, None] = 'bdd07dc4beb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('renderingentity', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'renderingentity', 'renderingentity', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'renderingentity', type_='foreignkey')
    op.drop_column('renderingentity', 'parent_id')
    # ### end Alembic commands ###
